name: 标准中文26键
author: 筋斗云
version: 1.0.0
url: https://github.com/Beyond-Input-Method/themes/default
create_time: 2023-03-30
update_time: 2023-03-30

# description: ""
# support_platforms: ""
# preview: ""
# dirPath: ""
# dirName: ""
